### ISSUE TITLE
Well, Fuck.

### ISSUE THREAD

**Issue by Jtfinlay** [IPPETAD/adventure.datetime#118]
This was from trying to delete an image.

12-02 22:03:02.799: ERROR/AndroidRuntime(18147): FATAL EXCEPTION: main
        Process: ca.cmput301f13t03.adventure_datetime, PID: 18147
        java.util.ConcurrentModificationException
        at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
        at ca.cmput301f13t03.adventure_datetime.model.StoryManager.deleteImage(StoryManager.java:370)
        at ca.cmput301f13t03.adventure_datetime.controller.AuthorController.deleteImage(AuthorController.java:116)
        at ca.cmput301f13t03.adventure_datetime.view.FullScreen_Image$3.onClick(FullScreen_Image.java:117)
        at android.view.View.performClick(View.java:4424)
        at android.view.View$PerformClick.run(View.java:18383)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4998)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:777)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:593)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by afontaine** [comment]
Sorry, but you guys have to deal with that... I have a paper to do. :crying_cat_face:
